services:
  # base de donnees
  #nom du service
  mysql:
    image: mysql:9
    ports:
      - 3306:3306
    volumes:
      - ./code/server/mysql:/app
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: KOMORA150813072002 
    restart: always
  server:
    image: node:23
    ports:
      - 3000:3000
    volumes:
      - ./code/server:/app
    tty: true
  client:
    image: node:23
    ports:
      - 5173:5173
    volumes:
      - ./code/client:/app
    tty: true

