name: Komora Shop CI

on:
  workflow_dispatch:

jobs:
  Execute_my_CI:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Clone github reposisitory
        uses: actions/checkout@v4
      - 
        name: Install server dependencies
        run: |
            cd code/server
            npm ci
      -
        name: Install client dependencies
        run: |
            cd code/client
            npm ci
      - 
        name: Compile server TypeScript files
        run: |
            cd code/server
            npm run compile
      -
        name: Compile client TypeScript files
        run: |
             cd code/client
             npm run build
      

    
