name: Komora Shop CI

on:
  workflow_dispatch:

jobs:
  Execute_my_CI:
    runs-on: ubuntu-latest
    steps:
      - name: Execute commands
        run: |
          ls
          mkdir test
          cd test
          touch index.html

          
    
